complete -c ffprobe -o L --description "show license"
complete -c ffprobe -o version --description "show version"
complete -c ffprobe -o h --description "show help"
complete -c ffprobe -o pretty --description "pretty print numerical values, more human readable"
complete -c ffprobe -o k --description " keep going even in case of error, always returns 0"
complete -c ffprobe -o read_packets --description "read packets info"
complete -c ffprobe -o read_frames --description "read frames info"
complete -c ffprobe -o show_files --description "show file info"
complete -c ffprobe -o show_frames  --description "show frames info, implies the option -read_frames and -read_packets"
complete -c ffprobe -o show_packets --description "show packets info, implies the option -read_packets"
complete -c ffprobe -o show_streams --description "show streams info"
complete -c ffprobe -o show_tags --description "show tags info"
